# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
VM_BOX = "ubuntu/focal64"
VM_BOX_URL = "https://mirrors.ustc.edu.cn/ubuntu-cloud-images/focal/current/focal-server-cloudimg-amd64-vagrant.box"
VM_HOSTNAME = "ubuntu-node-01"

ENV["VAGRANT_EXPERIMENTAL"] = "disks"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end

  config.vm.box = VM_BOX
  config.vm.box_url = VM_BOX_URL
  config.vm.hostname = VM_HOSTNAME
  config.vm.network "private_network", ip: "10.110.0.100", netmask: "23"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.disk :disk, size: "50GB", primary: true
  config.vm.disk :disk, size: "200GB", name: "extra_storage"
  config.vm.provider :virtualbox do |vb|
    vb.memory = 2048
    vb.cpus = 2
  end
end
